export const warriors_meta = ['Warrior ID', 'First Name', 'Last Name',' Position', 'Second Defense', 'Clan ID'];
export const warriors = [
  { warrior_id: 1, first_name: 'Kagami', last_name: 'Kaneie', position: 'H', second_defense: 'EM', clan_id: 6 },
  { warrior_id: 2, first_name: 'Kaede', last_name: 'Akiho', position: 'H', second_defense: 'Guide', clan_id: 7 },
  { warrior_id: 3, first_name: 'Taniguchi', last_name: 'Yamasato', position: 'H', second_defense: 'Guide', clan_id: 3 },
  { warrior_id: 4, first_name: 'Kamino', last_name: 'Mikoto', position: 'H', second_defense: 'Guide', clan_id: 7 },
  { warrior_id: 5, first_name: 'Nishikawa', last_name: 'Katsumi', position: 'C', second_defense: 'Guide', clan_id: 4 },
  { warrior_id: 6, first_name: 'Kawata', last_name: 'Terauchi', position: 'C', second_defense: 'EM', clan_id: 3 },
  { warrior_id: 7, first_name: 'Matsuzaki', last_name: 'Yoshimi', position: 'H', second_defense: 'T', clan_id: 3 },
  { warrior_id: 8, first_name: 'Hisaya', last_name: 'Yamasato', position: 'H', second_defense: 'EM', clan_id: 5 },
  { warrior_id: 9, first_name: 'Hazuki', last_name: 'Hazuki', position: 'H', second_defense: 'Guide', clan_id: 3 },
  { warrior_id: 10, first_name: 'Imai', last_name: 'Yoshimi', position: 'H', second_defense: 'Guide', clan_id: 2 },
  { warrior_id: 11, first_name: 'Moto', last_name: 'Matsuzaki', position: 'C', second_defense: 'T', clan_id: 3 },
  { warrior_id: 12, first_name: 'Enomoto', last_name: 'Sugai', position: 'C', second_defense: 'T', clan_id: 7 },
  { warrior_id: 13, first_name: 'Hazuki', last_name: 'Shigeri', position: 'C', second_defense: 'T', clan_id: 4 },
  { warrior_id: 14, first_name: 'Masatake', last_name: 'Nagisa', position: 'C', second_defense: 'SS', clan_id: 1 },
  { warrior_id: 15, first_name: 'Yoshimi', last_name: 'Akiho', position: 'H', second_defense: 'SS', clan_id: 7 },
  { warrior_id: 16, first_name: 'Akiho', last_name: 'Saito', position: 'H', second_defense: 'T', clan_id: 7 },
  { warrior_id: 17, first_name: 'Masatake', last_name: 'Mitsuyo', position: 'C', second_defense: 'T', clan_id: 4 },
  { warrior_id: 18, first_name: 'Kaneie', last_name: 'Mikoto', position: 'H', second_defense: 'SS', clan_id: 1 },
  { warrior_id: 19, first_name: 'Takejiro', last_name: 'Sugai', position: 'C', second_defense: 'SS', clan_id: 3 },
  { warrior_id: 20, first_name: 'Ejiri', last_name: 'Yoshikuni', position: 'C', second_defense: 'EM', clan_id: 1 },
  { warrior_id: 21, first_name: 'Kimoto', last_name: 'Taniguchi', position: 'C', second_defense: 'T', clan_id: 5 },
  { warrior_id: 22, first_name: 'Kaede', last_name: 'Katsumi', position: 'C', second_defense: 'T', clan_id: 1 },
  { warrior_id: 23, first_name: 'Terauchi', last_name: 'Nakamura', position: 'C', second_defense: 'EM', clan_id: 4 },
  { warrior_id: 24, first_name: 'Nagisa', last_name: 'Yamasato', position: 'H', second_defense: 'EM', clan_id: 3 },
  { warrior_id: 25, first_name: 'Ida', last_name: 'Mitsuyo', position: 'C', second_defense: 'Guide', clan_id: 5 },
  { warrior_id: 26, first_name: 'Kaneie', last_name: 'Yoshimi', position: 'H', second_defense: 'SS', clan_id: 6 },
  { warrior_id: 27, first_name: 'Mizushima', last_name: 'Kimoto', position: 'C', second_defense: 'SS', clan_id: 6 },
  { warrior_id: 28, first_name: 'Nagai', last_name: 'Tohaku', position: 'C', second_defense: 'Guide', clan_id: 4 },
  { warrior_id: 29, first_name: 'Kagami', last_name: 'Shinobu', position: 'C', second_defense: 'Guide', clan_id: 6 },
  { warrior_id: 30, first_name: 'Katzumi', last_name: 'Nagaoka', position: 'H', second_defense: 'T', clan_id: 3 },
  { warrior_id: 31, first_name: 'Shigeri', last_name: 'Ejiri', position: 'H', second_defense: 'T', clan_id: 7 },
  { warrior_id: 32, first_name: 'Yamasato', last_name: 'Sando', position: 'H', second_defense: 'EM', clan_id: 5 },
  { warrior_id: 33, first_name: 'Takejiro', last_name: 'Shinobu', position: 'C', second_defense: 'T', clan_id: 4 },
  { warrior_id: 34, first_name: 'Masanori', last_name: 'Kimoto', position: 'H', second_defense: 'Guide', clan_id: 4 },
  { warrior_id: 35, first_name: 'Edamura', last_name: 'Mizushima', position: 'C', second_defense: 'T', clan_id: 1 },
  { warrior_id: 36, first_name: 'Taniguchi', last_name: 'Hisaya', position: 'H', second_defense: 'Guide', clan_id: 5 },
  { warrior_id: 37, first_name: 'Mitsuyo', last_name: 'Ejiri', position: 'H', second_defense: 'Guide', clan_id: 6 },
  { warrior_id: 38, first_name: 'Tohaku', last_name: 'Mizushima', position: 'H', second_defense: 'Guide', clan_id: 6 },
  { warrior_id: 39, first_name: 'Saito', last_name: 'Kawata', position: 'C', second_defense: 'Guide', clan_id: 3 },
  { warrior_id: 40, first_name: 'Hisaya', last_name: 'Hazuki', position: 'C', second_defense: 'Guide', clan_id: 7 },
  { warrior_id: 41, first_name: 'Yahiro', last_name: 'Taniguchi', position: 'H', second_defense: 'Guide', clan_id: 6 },
  { warrior_id: 42, first_name: 'Masatake', last_name: 'Yoshikuni', position: 'H', second_defense: 'Guide', clan_id: 6 },
  { warrior_id: 43, first_name: 'Sando', last_name: 'Mitsuyo', position: 'C', second_defense: 'EM', clan_id: 4 },
  { warrior_id: 44, first_name: 'Edamura', last_name: 'Mayeda', position: 'C', second_defense: 'Guide', clan_id: 5 },
  { warrior_id: 45, first_name: 'Tohaku', last_name: 'Imai', position: 'H', second_defense: 'SS', clan_id: 6 },
  { warrior_id: 46, first_name: 'Motoki', last_name: 'Shigeri', position: 'H', second_defense: 'EM', clan_id: 1 },
  { warrior_id: 47, first_name: 'Masatake', last_name: 'Ida', position: 'C', second_defense: 'Guide', clan_id: 6 },
  { warrior_id: 48, first_name: 'Mizushima', last_name: 'Imai', position: 'C', second_defense: 'Guide', clan_id: 1 },
  { warrior_id: 49, first_name: 'Masanori', last_name: 'Ida', position: 'C', second_defense: 'SS', clan_id: 6 },
  { warrior_id: 50, first_name: 'Akiho', last_name: 'Yamasato', position: 'C', second_defense: 'SS', clan_id: 3 }
];

export const towns_meta = ['Town ID', 'Town Name', 'Defended by Clan ID'];
export const towns = [
  { town_id: 1, town_name: 'Musashino', clan_town_id: 1 },
  { town_id: 2, town_name: 'Tomisato', clan_town_id: 2 },
  { town_id: 3, town_name: 'Shinagawa', clan_town_id: 3 },
  { town_id: 4, town_name: 'Shinagawa', clan_town_id: 4 },
  { town_id: 5, town_name: 'Shinagawa', clan_town_id: 5 },
  { town_id: 6, town_name: 'Ikoma', clan_town_id: 6 },
  { town_id: 7, town_name: 'Izumo', clan_town_id: 7 }
];

export const clans_meta = ['Clan ID', 'Clan Name', 'Clan Size'];
export const clans = [
  { clan_id: 1, clan_name: 'Masanori Kagami', clan_size: 4 },
  { clan_id: 2, clan_name: 'Mitsuyo Kishi', clan_size: 6 },
  { clan_id: 3, clan_name: 'Sugai Taniguchi', clan_size: 4 },
  { clan_id: 4, clan_name: 'Mizushima Yoshimi', clan_size: 9 },
  { clan_id: 5, clan_name: 'Suzuki Kawata', clan_size: 10 },
  { clan_id: 6, clan_name: 'Kishi Nagisa', clan_size: 9 },
  { clan_id: 7, clan_name: 'Yoshikuni Imai', clan_size: 8 }
];

export const nemeses_meta = ['Nemesis ID', 'First Name', 'Last Name', 'Enemy of Clan ID'];
export const nemeses = [
  { nemesis_id: 1, first_name: 'Terauchi', last_name: 'Shigeri', clan_id: 1 },
  { nemesis_id: 2, first_name: 'Kamino', last_name: 'Hisaya', clan_id: 2 },
  { nemesis_id: 3, first_name: 'Misao', last_name: 'Yahiro', clan_id: 3 },
  { nemesis_id: 4, first_name: 'Imai', last_name: 'Taniguchi', clan_id: 4 },
  { nemesis_id: 5, first_name: 'Nagaoka', last_name: 'Nagisa', clan_id: 5 },
  { nemesis_id: 6, first_name: 'Nagai', last_name: 'Nagisa', clan_id: 6 },
  { nemesis_id: 7, first_name: 'Tatsuki', last_name: 'Jun', clan_id: 7 },
];

export const equipment_meta = ['Equipment ID', 'Sword Type', 'Assigned to Warrior ID'];
export const equipment = [
  { equipment_id: 1, sword_type: 'Tachi', warrior_id: 44 },
  { equipment_id: 2, sword_type: 'Kenjutsu', warrior_id: 49 },
  { equipment_id: 3, sword_type: 'Wakizashi', warrior_id: 46 },
  { equipment_id: 4, sword_type: 'Bokken', warrior_id: 15 },
  { equipment_id: 5, sword_type: 'Kenjutsu', warrior_id: 3 },
  { equipment_id: 6, sword_type: 'Wakizashi', warrior_id: 16 },
  { equipment_id: 7, sword_type: 'Naginata', warrior_id: 6 },
  { equipment_id: 8, sword_type: 'Uchigatana', warrior_id: 20 },
  { equipment_id: 9, sword_type: 'Katana', warrior_id: 35 },
  { equipment_id: 10, sword_type: 'Uchigatana', warrior_id: 13 },
  { equipment_id: 11, sword_type: 'Tanto', warrior_id: 5 },
  { equipment_id: 12, sword_type: 'Nagamaki', warrior_id: 30 },
  { equipment_id: 13, sword_type: 'Nagamaki', warrior_id: 26 },
  { equipment_id: 14, sword_type: 'Katana', warrior_id: 25 },
  { equipment_id: 15, sword_type: 'Odachi', warrior_id: 34 },
  { equipment_id: 16, sword_type: 'Tachi', warrior_id: 43 },
  { equipment_id: 17, sword_type: 'Kenjutsu', warrior_id: 9 },
  { equipment_id: 18, sword_type: 'Tachi', warrior_id: 4 },
  { equipment_id: 19, sword_type: 'Kenjutsu', warrior_id: 50 },
  { equipment_id: 20, sword_type: 'Tanto', warrior_id: 14 },
  { equipment_id: 21, sword_type: 'Kenjutsu', warrior_id: 24 },
];

export const defense_masters_meta = ['Master ID', 'Master Name', 'Master Ability'];
export const defense_masters = [
  { master_id: 1, master_name: 'Chiaki Shiro', master_ability: 'Supersonic Hearing' },
  { master_id: 2, master_name: 'Mitsuyo Yukimura', master_ability: 'Pacifist' },
  { master_id: 3, master_name: 'Nozomi Tatsuki', master_ability: 'Super Speed While Running Backwards' },
  { master_id: 4, master_name: 'Hisaya Kawata', master_ability: 'Sneezes With Eyes Open' },
  { master_id: 5, master_name: 'Ejiri Kaneie', master_ability: 'Super Speed While Running Backwards' },
  { master_id: 6, master_name: 'Kimoto Nagisa', master_ability: 'Hypersomnia' },
  { master_id: 7, master_name: 'Chiaki Nozomi', master_ability: 'No Fear of Spiders' },
  { master_id: 8, master_name: 'Chiaki Suzuki', master_ability: 'Invisible in Dark Rooms' },
  { master_id: 9, master_name: 'Katsumi Chiaki', master_ability: 'Pacifist' },
  { master_id: 10, master_name: 'Shiro Shigeri', master_ability: 'Sneezes With Eyes Open' },
  { master_id: 11, master_name: 'Motoki Edamura', master_ability: 'Pacifist' },
  { master_id: 12, master_name: 'Suzuki Sando', master_ability: 'Outside Voice Only' },
  { master_id: 13, master_name: 'Ida Yahiro', master_ability: 'Hypersomnia' },
  { master_id: 14, master_name: 'Jun Hisaya', master_ability: 'Invisible in Dark Rooms' },
  { master_id: 15, master_name: 'Masanori Enomoto', master_ability: 'Pacifist' },
  { master_id: 16, master_name: 'Yagi Shigeri', master_ability: 'Outside Voice Only' },
  { master_id: 17, master_name: 'Mizushima Ida', master_ability: 'Invisible in Dark Rooms' },
  { master_id: 18, master_name: 'Mitsuyo Kagami', master_ability: 'Sneezes With Eyes Open' },
  { master_id: 19, master_name: 'Nishikawa Shiro', master_ability: 'No Fear of Spiders' },
  { master_id: 20, master_name: 'Katsumi Katsumi', master_ability: 'No Fear of Spiders' },
  { master_id: 21, master_name: 'Shintaro Moto', master_ability: 'Outside Voice Only' }
];

export const warrior_masters_meta = ['Defense Master ID', 'Warrior ID'];
export const warrior_masters = [
  { master_id: 1, warrior_id: 27 },
  { master_id: 2, warrior_id: 23 },
  { master_id: 3, warrior_id: 18 },
  { master_id: 4, warrior_id: 37 },
  { master_id: 5, warrior_id: 31 },
  { master_id: 6, warrior_id: 34 },
  { master_id: 7, warrior_id: 9 },
  { master_id: 8, warrior_id: 4 },
  { master_id: 9, warrior_id: 7 },
  { master_id: 10, warrior_id: 15 },
  { master_id: 11, warrior_id: 5 },
  { master_id: 12, warrior_id: 29 },
  { master_id: 13, warrior_id: 33 },
  { master_id: 14, warrior_id: 41 },
  { master_id: 15, warrior_id: 16 },
  { master_id: 16, warrior_id: 43 },
  { master_id: 17, warrior_id: 19 },
  { master_id: 18, warrior_id: 8 },
  { master_id: 19, warrior_id: 28 },
  { master_id: 20, warrior_id: 24 },
  { master_id: 21, warrior_id: 11 },
]